tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#464747",
        "tertiary-container": "#b3b3b3",
        background: "#131313",
        "surface-container-low": "#1b1b1b",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-container": "#444545",
        "on-secondary-container": "#b7b5b4",
        primary: "#f2ca50",
        "on-primary-container": "#554300",
        "on-secondary": "#313030",
        "surface-tint": "#e9c349",
        "tertiary-fixed": "#e3e2e2",
        "secondary-container": "#474746",
        secondary: "#c8c6c5",
        "primary-fixed-dim": "#e9c349",
        "on-secondary-fixed": "#1c1b1b",
        outline: "#99907c",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-surface": "#e2e2e2",
        tertiary: "#cfcece",
        "on-background": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "on-primary-fixed-variant": "#574500",
        "primary-container": "#d4af37",
        "on-primary-fixed": "#241a00",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#d0c5af",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-highest": "#353535",
        "secondary-fixed": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#474746",
        "primary-fixed": "#ffe088",
        "on-tertiary": "#2f3031",
        "surface-bright": "#393939",
        "outline-variant": "#4d4635",
        "surface-container": "#1f1f1f",
        "on-primary": "#3c2f00",
        "surface-variant": "#353535",
        "inverse-surface": "#e2e2e2",
        "on-error": "#690005",
        surface: "#131313",
        "inverse-primary": "#735c00",
        error: "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        margin: "64px",
        "container-max": "1440px",
        gutter: "32px",
      },
      fontFamily: {
        "body-lg": ["Manrope"],
        "label-sm": ["Manrope"],
        "headline-lg": ["Noto Serif"],
        "headline-md": ["Noto Serif"],
        "body-md": ["Manrope"],
        "display-xl": ["Noto Serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "300" }],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "headline-lg": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
      },
    },
  },
};
